#pragma once
// GENERATED BY tools/generate_kernels.py. DO NOT EDIT
template <typename T>
struct OpInfo;

template <>
struct OpInfo<float> {
  static constexpr int add = 0;
  static constexpr int sub = 1;
  static constexpr int mul = 2;
  static constexpr int div = 3;
  static constexpr int negate = 4;
  static constexpr int abs = 5;
  static constexpr int min = 6;
  static constexpr int max = 7;
  static constexpr int sum = 8;
  static constexpr int product = 9;
};

template <>
struct OpInfo<int> {
  static constexpr int add = 10;
  static constexpr int sub = 11;
  static constexpr int mul = 12;
  static constexpr int div = 13;
  static constexpr int negate = 14;
  static constexpr int abs = 15;
  static constexpr int min = 16;
  static constexpr int max = 17;
  static constexpr int sum = 18;
  static constexpr int product = 19;
};

template <>
struct OpInfo<double> {
  static constexpr int add = 20;
  static constexpr int sub = 21;
  static constexpr int mul = 22;
  static constexpr int div = 23;
  static constexpr int negate = 24;
  static constexpr int abs = 25;
  static constexpr int min = 26;
  static constexpr int max = 27;
  static constexpr int sum = 28;
  static constexpr int product = 29;
};
