
class DPUOp:
    def __init__(self, name, symbol, type, kid):
        self.name = name
        self.symbol = symbol
        self.type = type
        self.kid = kid

class DPUBinaryOp(DPUOp):    
    def generate_macro(self, out):
        out.write(f"DEFINE_BINARY_KERNEL({self.type}, {self.name}, {self.symbol})\n")
    def kernel_name(self):
        return f"binary_{self.type}_{self.name}"
    @staticmethod
    def make(name, symbol):
        return lambda type, kid: DPUBinaryOp(name, symbol, type, kid)


class DPUUnaryOp(DPUOp):
    def generate_macro(self, out):
        out.write(f"DEFINE_UNARY_KERNEL({self.type}, {self.name}, {self.symbol})\n")
    def kernel_name(self):
        return f"unary_{self.type}_{self.name}"
    @staticmethod
    def make(name, symbol):
        return lambda type, kid: DPUUnaryOp(name, symbol, type, kid)
    

class DPUReduceOp(DPUOp):    
    def generate_macro(self, out):
        out.write(f"DEFINE_REDUCTION_KERNEL({self.type}, {self.name}, {self.symbol})\n")
    def kernel_name(self):
        return f"reduction_{self.type}_{self.name}"
    @staticmethod
    def make(name, symbol):
        return lambda type, kid: DPUReduceOp(name, symbol, type, kid)
    


def declare_unary_op(name, symbol):
    return lambda type, kid: DPUUnaryOp(name, symbol, type, kid)

categories = ['Binary', 'Unary', 'Reduction']

ops = [
    DPUBinaryOp.make('add', '+'),
    DPUBinaryOp.make('sub', '-'),
    DPUBinaryOp.make('mul', '*'),
    DPUBinaryOp.make('div', '/'),


    DPUUnaryOp.make('negate', 'NEGATE'),
    DPUUnaryOp.make('abs', 'ABS'),

    DPUReduceOp.make('min', 'MIN'),
    DPUReduceOp.make('max', 'MAX'),
    DPUReduceOp.make('sum', 'SUM'),
    DPUReduceOp.make('product', 'PRODUCT'),
]

types = [
    'float', 'int', 'double'
]

all_ops = [] # :: (KernelID, OpClass)
grouped_ops = []
kernel_id = 0
for type in types:
    group = []
    for op in ops:
        op_instance = op(type, kernel_id)
        all_ops.append((kernel_id, op_instance))
        group.append(op_instance)
        kernel_id += 1
    grouped_ops.append((type, group))


with open("dpu/kernels.h", "w") as out:
    out.write('// GENERATED BY tools/generate_kernels.py. DO NOT EDIT\n')
    out.write('#include "./binary.inl"\n')
    out.write('#include "./reduce.inl"\n')
    out.write('#include "./unary.inl"\n')
    for id, op in all_ops:
        out.write(f'#define KERNEL_ID_{op.kernel_name().upper()} {id}\n')
    for id, op in all_ops:
        op.generate_macro(out)
    out.write(f'#define KERNEL_COUNT {len(all_ops)}\n')
    out.write('int (*kernels[KERNEL_COUNT])(void) = {\n')
    for id, op in all_ops:
        out.write(f'    {op.kernel_name()}, // {id}\n')
    out.write('};\n')



with open("host/opinfo.h", "w") as out:
    out.write('#pragma once\n')
    out.write('// GENERATED BY tools/generate_kernels.py. DO NOT EDIT\n')
    out.write('template<typename T> struct OpInfo;\n\n')
    for type, group in grouped_ops:
        out.write(f'template<> struct OpInfo<{type}> {{\n')
        for op in group:
            out.write(f'    static constexpr int {op.name} = {op.kid};\n')
        out.write('};\n\n')

with open("host/kernelids.h", "w") as out:
    out.write('#pragma once\n\n')
    out.write('#include <common.h>\n')
    out.write('// GENERATED BY tools/generate_kernels.py. DO NOT EDIT\n')
    out.write('enum KernelTypes {\n')
    for t in types:
        out.write(f'    KERNEL_TYPE_{t.upper()},\n')
    out.write('};\n')

    out.write(f'enum KernelOperator {{\n')
    for op in ops:
        fake = op('float', 0)
        out.write(f'    KERNEL_OP_{fake.name.upper()},\n')
    out.write('};\n')

    out.write('struct KernelInfo {\n')
    out.write('    int id;\n')
    out.write('    KernelTypes type;\n')
    out.write('    KernelCategory category;\n')
    out.write('    KernelOperator op;\n')
    out.write('    const char *name;\n')
    out.write('};\n')

    # make an array of the info that we have from all_ops
    out.write('static KernelInfo kernel_infos[] = {\n')
    for id, op in all_ops:
        if isinstance(op, DPUBinaryOp):
            category = 'KERNEL_BINARY'
        elif isinstance(op, DPUUnaryOp):
            category = 'KERNEL_UNARY'
        elif isinstance(op, DPUReduceOp):
            category = 'KERNEL_REDUCTION'
        else:
            category = 'KERNEL_UNKNOWN'
        name = f'"{op.kernel_name().upper()}"'
        out.write(f'    {{ {id}, KERNEL_TYPE_{op.type.upper()}, {category}, KERNEL_OP_{op.name.upper()}, {name} }},\n')
    out.write('};\n')
